### ISSUE TITLE
binwrap install fails (powershell/windows 10)

### ISSUE THREAD

**Issue by harrysarson** [avh4/binwrap#35]
Hi! I got the following error installing the latest version of `elm-format`:

```
PS C:\Users\harry\node\elm-test> npm i -g elm-format
C:\Users\harry\AppData\Roaming\npm\elm-format -> C:\Users\harry\AppData\Roaming\npm\node_modules\elm-format\bin\elm-format

> elm-format@0.8.2 install C:\Users\harry\AppData\Roaming\npm\node_modules\elm-format
> binwrap-install

internal/buffer.js:53
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 5. Received 9
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt32LE (internal/buffer.js:109:5)
    at UnzipStream._readExtraFields (C:\Users\harry\AppData\Roaming\npm\node_modules\elm-format\node_modules\unzip-stream\lib\unzip-stream.js:443:49)
    at UnzipStream.processDataChunk (C:\Users\harry\AppData\Roaming\npm\node_modules\elm-format\node_modules\unzip-stream\lib\unzip-stream.js:213:30)
    at UnzipStream._parseOrOutput (C:\Users\harry\AppData\Roaming\npm\node_modules\elm-format\node_modules\unzip-stream\lib\unzip-stream.js:651:28)
    at PassThrough.done (C:\Users\harry\AppData\Roaming\npm\node_modules\elm-format\node_modules\unzip-stream\lib\unzip-stream.js:713:18)
    at Object.onceWrapper (events.js:273:13)
    at PassThrough.emit (events.js:182:13)
    at finishMaybe (_stream_writable.js:641:14)
    at afterWrite (_stream_writable.js:481:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm-format@0.8.2 install: `binwrap-install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elm-format@0.8.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\harry\AppData\Roaming\npm-cache\_logs\2019-08-11T11_03_04_421Z-debug.log
PS C:\Users\harry\node\elm-test> node -v
v10.15.0
PS C:\Users\harry\node\elm-test> npm -v
6.9.0
```

**Comment by harrysarson** [comment]
To see an example of this failure, try this pull request I made: https://github.com/rtfeldman/node-test-runner/pull/378.

Here is the CI failure for windows: https://ci.appveyor.com/project/rtfeldman/node-test-runner/builds/26617374/job/o2d41doelh97oa8n.

**Comment by avh4** [comment]
the stack trace seems to show that the unzip library couldn't parse the zip file.  Are you able to tell whether the downloaded zip file is corrupted or not?

**Comment by harrysarson** [comment]
In a new directory I ran `$npm init` and `$npm install elm-format` (giving same error as above).
This is the result: [elm-format.zip](https://github.com/avh4/binwrap/files/3490218/elm-format.zip), where should I look for the downloaded zip file? I found `\node_modules\elm-format\unpacked_bin\elm-format.exe` but got the following when trying to run it:

```
Program 'elm-format.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1
+ .\elm-format.exe
+ ~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\elm-format.exe
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

I could not find the downloaded zip file.

**Comment by harrysarson** [comment]
I download the zip file from github releases directly and everything is fine (zip file is valid and elm-format.exe runs).

**Comment by avh4** [comment]
hmm, okay

I was able to reproduce with node 12.8.0, npm 6.10.2, Windows 2012

**Comment by avh4** [comment]
I was able to reproduce this on Mac (forcing binwrap to download and unzip the windows binaries) by doing:

```
# in a clean directory
npm install --ignore-scripts elm-format
BINWRAP_PLATFORM=win32 ./node_modules/.bin/elm-format
```

**Comment by avh4** [comment]
So it seems like the published elm-format zip file doesn't work with unzip-stream

**Comment by avh4** [comment]
Ah, I'm suspecting the issue is that I made the elm-format 0.8.2 zip files with level 9 compression, which maybe is not a standard compression level

**Comment by avh4** [comment]
The compression level of the zipfile doesn't seem to matter,  but the zip files produced by the Windows version of infozip appear to not work, whereas zipfiles created by the Mac OS version of Infozip (Zip 3.0 (July 5th 2008)) do work.

**Comment by avh4** [comment]
I replaced the published elm-format zip, so hopefully that works now.  I also created #36 to help prevent this in the future, and #37 as a related issue that was exposed here.

**Comment by harrysarson** [comment]
I checked the install and it works now! Thanks @avh4 :)
